baseURL = "https://example.com"
languageCode = "en-us"
title = "Calvin Log"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Calvin"
  homepage = "https://joway.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
disqus = "calvin-2" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://www.calvinmorett.com"
