baseURL = "https://example.com"
languageCode = "en-us"
title = "Supposed to be a blog about what Calvin is working on"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Calvin"
  homepage = "https://calvinmorett.com"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
disqus = "calvin-2" # disqus account name
extraHead = ''
mainSections = ["posts"]
headTitle = "index"

[[params.socials]]
name = "Back"
link = "javascript:history.back()"
