baseURL = "https://example.com"
languageCode = "en-us"
title = "Calvin's Progress and What he's working on."
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Calvin"
  homepage = "https://calvinmorett.com"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
disqus = "calvin-2" # disqus account name
extraHead = ''
mainSections = ["posts"]
headTitle = "Progress Log"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://www.calvinmorett.com"
